### ISSUE TITLE
packaging dependency missing

### ISSUE THREAD

**Issue by jwodder** [jaraco/pip-run#49]
[This commit](https://github.com/jaraco/pip-run/commit/589fa31f04342142cbe8ea5f4162319c54c8eb76) added the line `import packaging.requirements` to the code, but `packaging` was not added as a dependency for the project.  Trying to use pip-run in a fresh environment thus fails with `ModuleNotFoundError: No module named 'packaging'`.

**Comment by jaraco** [comment]
Oops. Thanks for reporting. Will be fixed forthwith.
