### ISSUE TITLE
app_paths dependency is a nuisance

### ISSUE THREAD

**Issue by jaraco** [jaraco/pip-run#64]
Per https://github.com/jaraco/pip-run/commit/346392685903dfcd1414e438c734ac4263047665#r94301964, @mgorny reports that the app_paths dependency is problemmatic. Let's explore ways to fix that.

**Comment by jaraco** [comment]
Filed a request as https://github.com/alexdelorenzo/app_paths/issues/3.

**Comment by jaraco** [comment]
Reported issues:

> Its GitHub repository seems not to be up-to-date, it doesn't have tests, it still uses old appdirs and brings a bunch of NIH packages. This makes pip-run a true PITA to package.

I checked on the "old appdirs" and that appears not to be an issue:

```
 ~ $ pip-run pipdeptree -- -m pipdeptree
happybase==1.2.0
  - six [required: Any, installed: 1.16.0]
  - thriftpy2 [required: >=0.4, installed: 0.4.16]
    - ply [required: >=3.4,<4.0, installed: 3.11]
    - six [required: ~=1.15, installed: 1.16.0]
pip-run==9.3.0
  - app-paths [required: Any, installed: 0.0.7]
    - aiopath [required: >=0.6.9, installed: 0.6.11]
      - aiofile [required: >=3.5.0,<4, installed: 3.8.1]
        - caio [required: ~=0.9.0, installed: 0.9.11]
      - anyio [required: >=3.2.0,<4, installed: 3.6.2]
        - idna [required: >=2.8, installed: 3.4]
        - sniffio [required: >=1.1, installed: 1.3.0]
    - appdirs [required: Any, installed: 1.4.4]
    - asyncstdlib [required: >=3.9.2,<4.0.0, installed: 3.10.5]
    - StrEnum [required: >=0.4.6, installed: 0.4.9]
    - unpackable [required: >=0.0.4,<0.1.0, installed: 0.0.4]
  - autocommand [required: Any, installed: 2.2.1]
  - jaraco.context [required: Any, installed: 4.2.0]
  - jaraco.text [required: Any, installed: 3.11.0]
    - autocommand [required: Any, installed: 2.2.1]
    - inflect [required: Any, installed: 6.0.2]
      - pydantic [required: >=1.9.1, installed: 1.10.2]
        - typing-extensions [required: >=4.1.0, installed: 4.4.0]
    - jaraco.context [required: >=4.1, installed: 4.2.0]
    - jaraco.functools [required: Any, installed: 3.5.2]
      - more-itertools [required: Any, installed: 9.0.0]
    - more-itertools [required: Any, installed: 9.0.0]
  - more-itertools [required: >=8.3, installed: 9.0.0]
  - packaging [required: Any, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - path [required: >=15.1, installed: 16.5.0]
  - pip [required: >=19.3, installed: 22.3.1]
pipdeptree==2.3.3
setuptools==65.6.3
wheel==0.38.4
```

Where did you get the impression that it depends on an old appdirs?

**Comment by jaraco** [comment]
> NIH packages

Can you elaborate a bit on what an NIH package is and which dependencies are (most) concerning? I could guess, but I'd like to understand your perspective better. I do agree, at least for my usage, a thin wrapper around appdirs with fewer dependencies would be nice.

**Comment by mgorny** [comment]
> I checked on the "old appdirs"

I'm sorry for not being precise. I meant it is using `appdirs` rather than `platformdirs`, given that apparently the latter is the preferred package these days.

> Can you elaborate a bit on what an NIH package is and which dependencies are (most) concerning?

In my case, it means having to package `aiopath`, `aiofile`, `caio`, `StrEnum` and `unpackable`. I haven't checked the "quality" of these packages yet (e.g. if they have working tests) but you can imagine this feels like a lot of work given how small a package pip-run feels to be.

On top of that, we already have `aiofiles` and I'm wondering how different it is from `aiofile`.

**Comment by jaraco** [comment]
Please feel free not to invest the time/energy into packaging those downstream dependencies until this issue is resolved. I agree that a likely outcome should be to reduce the dependency tree here.

**Comment by jaraco** [comment]
Looks like `platformdirs` [has the pathlib functionality needed](https://github.com/platformdirs/platformdirs/issues/41#issuecomment-1366000954).

**Comment by mgorny** [comment]
Thanks a lot!
