### ISSUE TITLE
Improve support for standalone scripts with shebang lines and possible "reinvocation"

### ISSUE THREAD

**Issue by sirosen** [jaraco/pip-run#78]
I've been trying to upgrade some scripts in my `~/bin` to use `pip-run`, and I'd like them to bootstrap themselves so that they can
- be fully self-contained
- have a valid shebang line

So an example of what I have today would be
```python
#!/usr/bin/env python
# Requirements:
# requests
try:
    import requests
except ImportError:
    import os
    import shutil
    import sys

    path = shutil.which("pip-run")
    if not path:
        print("pip-run not found", file=sys.stderr)
        sys.exit(1)
    os.execv(path, [path, "--", sys.argv[0]])

print(requests.get("some-url").content)
```

This is a little brittle but it seems to work.

The next thing I wanted was to catch the case in which the `pip-run` invocation has happened, but some requirement was not satisfied (e.g. because there's a typo in the requirements data). To do this, I need to pass some additional information to the `pip-run` invocation to indicate that it's been called already. I seem to get what I want by injecting an environment variable and switching to `execve`:
```python
try:
    import requests
except ImportError:
    if os.getenv("PIP_RUN_INVOKED_ONCE") == "1":
        print("pip-run did not satisfy requirements", file=sys.stderr)
        sys.exit(1)

    path = shutil.which("pip-run")
    if not path:
        print("pip-run not found", file=sys.stderr)
        sys.exit(1)
    env = os.environ.copy()
    env["PIP_RUN_INVOKED_ONCE"] = "1"
    os.execve(path, [path, "--", sys.argv[0]], env)
```

All of this is great! It's a relatively small bit of boilerplate to add to my scripts to get "self-invoking" `pip-run` usage in my personal `bin/` dir. But it seems like there's room for improvement. The first thing that comes to mind is that it would be nice if `PIP_RUN_INVOKED_ONCE` was set for me by `pip-run`.
The other thing which would be awesome is if I could switch to using `#!/usr/bin/env pip-run` and have that work. Unfortunately, that doesn't play nicely if the script name isn't `.py` (and mine are generally not).

There might be other ways to improve things in `#!/usr/bin/env pip-run` is supported as a usage pattern, so I do not want to limit this feature request to an env var or shebang-style usage.

**Comment by majutsushi** [comment]
You can use `env`'s `-S` option to pass the `--` parameter to `pip-run`. Setting the shebang to `#!/usr/bin/env -S pip-run --` works fine for me in a simple test. I'm not sure which `env` versions other than GNU env and FreeBSD support that option, though.

**Comment by sirosen** [comment]
Thanks for sharing! I wasn't aware of the `env -S` workaround for handling multiple arguments. I'm sure I'll find that handy.

FWIW, I ended up writing my own little launcher because the penalty paid for building all venvs dynamically was a little too much for me.

I still think it would be nice if the simple `#!/usr/bin/env pip-run` line worked. Maybe by seeing that the following two things hold?
- `shutil.which` reports the first and only argument as being something in the path
- reading the shebang line matches `#![^\s]*/env pip-run]`

**Comment by jaraco** [comment]
> FWIW, I ended up writing my own little launcher because the penalty paid for building all venvs dynamically was a little too much for me.

Since #63, pip-run supports caching environments. Does that `PIP_RUN_MODE=persist` not address the penalty? If not, please consider opening an issue for that.



> You can use `env`'s `-S` option to pass the `--` parameter to `pip-run`. Setting the shebang to `#!/usr/bin/env -S pip-run --` works fine for me in a simple test. I'm not sure which `env` versions other than GNU env and FreeBSD support that option, though.

I tried it out on macOS and it works great:

```
 draft @ cat > foo
#!/usr/bin/env -S pip-run -- 

__requires__ = ['requests']

import requests
 draft @ chmod u+x foo
 draft @ ./foo
 draft @ ./foo && echo 'worked'
worked
```

> Unfortunately, that doesn't play nicely if the script name isn't .py (and mine are generally not).

I don't think it would be hard or dangerous to change the [python arg inference](https://github.com/jaraco/pip-run/blob/5999904a30a55155934e76f59d43ec55447be421/pip_run/commands.py#L17-L18) to honor a file a shebang header referencing either Python or pip-run. The hardest part is probably making sure the behavior is covered by tests.

With something like that in place, the shebang header could be simply `/usr/bin/env pip-run` or `/usr/bin/env py -m pip-run`.

Do you agree this simple change would satisfy all of the concerns? Would you be interested in working on the implementation?

> it would be nice if `PIP_RUN_INVOKED_ONCE` was set for me by `pip-run`.

This behavior seems reasonable, at least as a secret feature. I'd probably design it slightly differently so that a callee could distinguish between: `pip-run myscript` and `pip-run requests -- -m pip-run myscript` (where there are multiple layers of pip-run). Maybe `PIP_RUN_DEPTH`, which would be incremented by pip-run on each invocation. For your purposes, you could simply use `os.environ.get('PIP_RUN_DEPTH')` as the signal.

Then again, if you get shebang support, you wouldn't need to handle imports at all. The pip-run design is meant to avoid having to have conditional imports. Let's shelve this idea until the dust settles on shebang support.

**Comment by sirosen** [comment]
First things first, thanks for the comprehensive info and feedback!

> Since #63, pip-run supports caching environments. Does that `PIP_RUN_MODE=persist` not address the penalty? If not, please consider opening an issue for that.

I wasn't aware of this option. It definitely helps a lot -- I'll want to read about the behavior a bit to see if it fully covers my use-cases. If I find a gap, I'll open a fresh issue.



> I don't think it would be hard or dangerous to change the [python arg inference](https://github.com/jaraco/pip-run/blob/5999904a30a55155934e76f59d43ec55447be421/pip_run/commands.py#L17-L18) to honor a file a shebang header referencing either Python or pip-run. The hardest part is probably making sure the behavior is covered by tests.
> 
> With something like that in place, the shebang header could be simply `/usr/bin/env pip-run` or `/usr/bin/env py -m pip-run`.
> 
> Do you agree this simple change would satisfy all of the concerns? Would you be interested in working on the implementation?

Yes and yes! We can have a deeper discussion about exactly what shebang lines should be supported once I come back with a PR with a first draft. I'm excited to be able to contribute back to the project. :smile: 

> This behavior seems reasonable, at least as a secret feature. 
> ...
> Then again, if you get shebang support, you wouldn't need to handle imports at all. The pip-run design is meant to avoid having to have conditional imports. Let's shelve this idea until the dust settles on shebang support.

Yeah, I fully agree. I was only looking for this feature because I was missing the other support I wanted. It _might_ be nice to expose that a script is running under `pip-run`, but it's not necessarily part of this issue.
